### ISSUE TITLE
java.lang.IllegalStateException: unsupported when.

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/auto-visitor#23]
```
java.lang.IllegalStateException: unsupported when. requires when (param) {}
	at com.anatawa12.autoVisitor.compiler.caller.FunctionCallTransformer.unsupportedWhenExpr(FunctionCallTransformer.kt:298)
	at com.anatawa12.autoVisitor.compiler.caller.FunctionCallTransformer.visitCall(FunctionCallTransformer.kt:152)
```

**Comment by anatawa12** [comment]
for functions in class/object
